Move disk 1 from pole 1 to pole 2
Move disk 2 from pole 1 to pole 3
Move disk 1 from pole 2 to pole 3
Move disk 3 from pole 1 to pole 2
Move disk 1 from pole 3 to pole 1
Move disk 2 from pole 3 to pole 2
Move disk 1 from pole 1 to pole 2
Move disk 4 from pole 1 to pole 3
Move disk 1 from pole 2 to pole 3
Move disk 2 from pole 2 to pole 1
Move disk 1 from pole 3 to pole 1
Move disk 3 from pole 2 to pole 3
Move disk 1 from pole 1 to pole 2
Move disk 2 from pole 1 to pole 3
Move disk 1 from pole 2 to pole 3
Move disk 5 from pole 1 to pole 2
Move disk 1 from pole 3 to pole 1
Move disk 2 from pole 3 to pole 2
Move disk 1 from pole 1 to pole 2
Move disk 3 from pole 3 to pole 1
Move disk 1 from pole 2 to pole 3
Move disk 2 from pole 2 to pole 1
Move disk 1 from pole 3 to pole 1
Move disk 4 from pole 3 to pole 2
Move disk 1 from pole 1 to pole 2
Move disk 2 from pole 1 to pole 3
Move disk 1 from pole 2 to pole 3
Move disk 3 from pole 1 to pole 2
Move disk 1 from pole 3 to pole 1
Move disk 2 from pole 3 to pole 2
Move disk 1 from pole 1 to pole 2
